project_id = "piyvinbuxpnquwzyugdj"

[functions.create-user-account]
verify_jwt = false

[functions.donations-stats]
verify_jwt = false

[functions.get-payment-config]
verify_jwt = false

[functions.process-adhesion]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-presence-reminders]
verify_jwt = false

[functions.send-reunion-cr]
verify_jwt = false
